server:
  port : 8080

spring:
  application:
    name: cardapio-semanal
  liquibase:
    change-log: 'classpath:db/database-change-log.yaml'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        default_schema: public
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  sql:
    init:
      mode: always
      platform: postgres